export const HIGH_DEMAND_SERVICES = [
  "Google Business Profile Optimization",
  "Website Redesign",
  "CRM Setup & Automation",
  "WhatsApp Follow-Up Automation",
  "Call Tracking Setup",
  "Appointment Booking System",
  "Review Automation System",
  "Ads Conversion Tracking Setup",
  "Local SEO Services",
  "Email Marketing Automation",
  "Lead Capture System",
  "Social Media Automation",
  "Facebook Ads Setup",
  "Google Search Ads Setup",
  "Website Speed Optimization",
  "Landing Page Build",
  "Quote & Invoice Automation",
  "Chatbot Setup",
  "Sales Funnel Build",
  "Reputation Management",
  "Missed Call Text-Back System",
  "Customer Database Setup",
  "Google Maps Ranking Boost",
  "E-commerce Setup",
  "White-Label Virtual Assistant"
];