import React, { useState } from 'react';
import { BusinessData } from '../types';
import { Icons } from './Icons';
import { jsPDF } from "jspdf";

interface Props {
  data: BusinessData;
  languageMode: 'en' | 'bn'; // New prop
}

const ScoreBar = ({ value, colorClass }: { value: number; colorClass: string }) => (
  <div className="w-full bg-gray-200 rounded-full h-2 dark:bg-gray-700 mt-1.5 overflow-hidden">
    <div className={`h-full rounded-full ${colorClass}`} style={{ width: `${value}%` }}></div>
  </div>
);

export const BusinessRow: React.FC<Props> = ({ data, languageMode }) => {
  const [expanded, setExpanded] = useState(false);
  const [activeTab, setActiveTab] = useState<'details' | 'outreach'>('details');
  const [copied, setCopied] = useState(false);

  // Helper to choose text based on language mode
  const t = (en: any, bn?: any) => (languageMode === 'bn' && bn && bn.length > 0 ? bn : en);

  // Calculate age if yearFounded is a valid 4-digit year
  const currentYear = new Date().getFullYear();
  const foundedYear = parseInt(data.yearFounded);
  const businessAge = !isNaN(foundedYear) && foundedYear > 1000 && foundedYear <= currentYear 
    ? currentYear - foundedYear 
    : null;

  const downloadProfilePDF = (e: React.MouseEvent) => {
    e.stopPropagation();
    const doc = new jsPDF();
    
    // Header Section
    doc.setFillColor(243, 244, 246); // gray-100
    doc.rect(0, 0, 210, 40, 'F');
    
    doc.setFontSize(22);
    doc.setTextColor(31, 41, 55); // gray-800
    doc.text(data.businessName, 14, 20);
    
    doc.setFontSize(10);
    doc.setTextColor(75, 85, 99); // gray-600
    doc.text(`${data.category}  |  Founded: ${data.yearFounded}  |  Rating: ${data.googleRating} (${data.totalReviews} reviews)`, 14, 28);

    let y = 55;

    // 1. Contact & Location
    doc.setFontSize(14);
    doc.setTextColor(37, 99, 235); // blue-600
    doc.text("Contact & Location", 14, y);
    y += 10;
    
    doc.setFontSize(10);
    doc.setTextColor(55);
    doc.text(`Address:`, 14, y); 
    doc.setTextColor(0);
    const splitAddr = doc.splitTextToSize(data.address, 120);
    doc.text(splitAddr, 35, y);
    y += (splitAddr.length * 5) + 3;

    doc.setTextColor(55);
    doc.text(`Phone:`, 14, y); doc.setTextColor(0); doc.text(data.phone, 35, y); y += 6;
    doc.setTextColor(55);
    doc.text(`Email:`, 14, y); doc.setTextColor(0); doc.text(data.email, 35, y); y += 6;
    doc.setTextColor(55);
    doc.text(`Website:`, 14, y); doc.setTextColor(0); doc.text(data.website, 35, y); y += 12;

    // 2. Scores
    doc.setFontSize(14);
    doc.setTextColor(22, 163, 74); // green-600
    doc.text("AI Intelligence Scores", 14, y);
    y += 10;

    const scoreY = y;
    doc.setFontSize(10);
    doc.setTextColor(55);
    
    // Column 1
    doc.text(`Lead Gen Score:`, 14, scoreY); 
    doc.setFont("helvetica", "bold"); doc.text(`${data.leadGenScore}/100`, 50, scoreY); doc.setFont("helvetica", "normal");
    
    doc.text(`Strength Score:`, 14, scoreY + 6); 
    doc.setFont("helvetica", "bold"); doc.text(`${data.strengthScore}/100`, 50, scoreY + 6); doc.setFont("helvetica", "normal");

    // Column 2
    doc.text(`Engagement Score:`, 80, scoreY); 
    doc.setFont("helvetica", "bold"); doc.text(`${data.engagementScore}/100`, 120, scoreY); doc.setFont("helvetica", "normal");

    doc.text(`Conversion Prob:`, 80, scoreY + 6); 
    doc.setFont("helvetica", "bold"); doc.text(`${data.conversionProb}%`, 120, scoreY + 6); doc.setFont("helvetica", "normal");

    y += 20;

    // 3. Digital Presence
    doc.setFontSize(14);
    doc.setTextColor(147, 51, 234); // purple-600
    doc.text("Digital Health", 14, y);
    y += 10;
    
    doc.setFontSize(10);
    doc.setTextColor(55);
    doc.text(`SSL Status: ${data.sslStatus}`, 14, y);
    doc.text(`Mobile Friendly: ${data.mobileFriendly}`, 80, y);
    doc.text(`Domain Authority: ${data.domainAuthority}`, 140, y);
    y += 15;

    // 4. Sales Opps (PDF always English for simplicity/font compatibility)
    doc.setFontSize(14);
    doc.setTextColor(234, 88, 12); // orange-600
    doc.text("Top Sales Opportunities", 14, y);
    y += 8;
    doc.setFontSize(10);
    doc.setTextColor(55);
    data.salesOpportunities.forEach(opp => {
        doc.text(`- ${opp}`, 14, y);
        y += 6;
    });
    y += 5;

    // 5. Strategic Summary (English)
    doc.setFontSize(14);
    doc.setTextColor(234, 88, 12); // orange-600
    doc.text("Strategic Analysis", 14, y);
    y += 8;
    
    doc.setFontSize(10);
    doc.setTextColor(0);
    const summaryLines = doc.splitTextToSize(data.summary, 180);
    doc.text(summaryLines, 14, y);
    y += (summaryLines.length * 5) + 10;
    
    // Footer
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by GeoLead Pro on ${new Date().toLocaleDateString()}`, 14, 285);

    doc.save(`${data.businessName.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_profile.pdf`);
  };

  // --- OUTREACH GENERATOR LOGIC ---
  const generateOutreach = () => {
    const isNoWebsite = !data.website || data.website === 'N/A';
    const isLowRating = data.googleRating < 4.5;
    const isNoSocials = !data.facebook && !data.instagram && !data.linkedin;
    
    let subject = "";
    let body = "";

    if (isNoWebsite) {
      subject = `Question about ${data.businessName}'s website`;
      body = `Hi Team,\n\nI was looking for ${data.businessName} online to check your services, but I couldn't find a website. I specialize in building high-converting websites for ${data.category} businesses.\n\nWould you be open to a quick chat about getting you online?`;
    } else if (isLowRating) {
      subject = `Quick tip for ${data.businessName}'s Google reviews`;
      body = `Hi Team,\n\nI noticed ${data.businessName} has a ${data.googleRating} star rating. I help ${data.category} businesses improve their reputation and get more 5-star reviews automatically.\n\nI have a strategy that could help bump that up quickly. Worth a chat?`;
    } else if (isNoSocials) {
      subject = `Missing you on social media`;
      body = `Hi Team,\n\nI was searching for ${data.businessName} on social media but couldn't find active profiles. Your competitors in ${data.serviceArea} are getting a lot of traction there.\n\nI'd love to show you a simple plan to get more leads from Facebook and Instagram.`;
    } else {
      subject = `Partnership opportunity with ${data.businessName}`;
      body = `Hi Team,\n\nI've been analyzing top ${data.category} businesses in ${data.serviceArea} and ${data.businessName} stood out. I see a few easy wins to get you more customers this month.\n\nAre you open to a 5-minute idea sharing call?`;
    }

    return { subject, body };
  };

  const outreachContent = generateOutreach();

  const handleCopy = () => {
    navigator.clipboard.writeText(`Subject: ${outreachContent.subject}\n\n${outreachContent.body}`);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <>
      <tr 
        className={`bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600 transition-colors cursor-pointer ${expanded ? 'bg-blue-50 dark:bg-gray-700' : ''}`}
        onClick={() => setExpanded(!expanded)}
      >
        <td className="p-4 w-4">
          {expanded ? <Icons.ChevronDown size={16} /> : <Icons.ChevronRight size={16} />}
        </td>
        <td className="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
          <div className="flex flex-col">
            <span className="text-base font-bold">{data.businessName}</span>
            <span className="text-xs text-gray-500">{data.category} • {data.yearFounded}</span>
          </div>
        </td>
        <td className="px-6 py-4 text-gray-600 dark:text-gray-300">
          <div className="flex items-center gap-1 text-sm">
             <span className="text-yellow-500 font-bold">★ {data.googleRating}</span>
             <span className="text-xs text-gray-400">({data.totalReviews})</span>
          </div>
        </td>
        <td className="px-6 py-4">
          <div className="flex flex-col gap-1 w-32">
            <div className="flex justify-between text-xs mb-0.5">
              <span>Leads</span>
              <span className="font-bold">{data.leadGenScore}</span>
            </div>
            <ScoreBar value={data.leadGenScore} colorClass="bg-green-500" />
          </div>
        </td>
        <td className="px-6 py-4 text-sm text-gray-500 dark:text-gray-400 max-w-xs truncate">
          {data.address}
        </td>
        <td className="px-6 py-4 text-right">
          <div className="flex justify-end gap-2 items-center">
            {/* Individual PDF Download */}
            <button 
                onClick={downloadProfilePDF}
                className="text-gray-500 hover:text-red-600 transition-colors p-1"
                title="Download Profile PDF"
            >
                <Icons.FileText size={18} />
            </button>

            {data.website && (
              <a href={data.website} target="_blank" rel="noreferrer" className="text-blue-600 hover:text-blue-800 p-1" onClick={(e) => e.stopPropagation()}>
                <Icons.Globe size={18} />
              </a>
            )}
            <a href={`https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(data.businessName + " " + data.address)}`} target="_blank" rel="noreferrer" className="text-green-600 hover:text-green-800 p-1" onClick={(e) => e.stopPropagation()}>
              <Icons.MapPin size={18} />
            </a>
          </div>
        </td>
      </tr>

      {/* EXPANDED DETAILS */}
      {expanded && (
        <tr className="bg-gray-50 dark:bg-gray-800/50">
          <td colSpan={6} className="p-0">
            {/* TABS HEADER */}
            <div className="flex border-b border-gray-200 dark:border-gray-700 px-6 pt-4 bg-white dark:bg-gray-800">
               <button 
                 onClick={(e) => { e.stopPropagation(); setActiveTab('details'); }}
                 className={`pb-3 px-4 text-sm font-medium border-b-2 transition-colors ${activeTab === 'details' ? 'border-blue-600 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700'}`}
               >
                 Business Intelligence
               </button>
               <button 
                 onClick={(e) => { e.stopPropagation(); setActiveTab('outreach'); }}
                 className={`pb-3 px-4 text-sm font-medium border-b-2 transition-colors flex items-center gap-2 ${activeTab === 'outreach' ? 'border-purple-600 text-purple-600' : 'border-transparent text-gray-500 hover:text-gray-700'}`}
               >
                 <Icons.MessageSquare size={16} /> Outreach Generator
               </button>
            </div>

            {/* TAB CONTENT: DETAILS */}
            {activeTab === 'details' && (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6 p-6 border-b border-gray-200 dark:border-gray-700">
              
              {/* Identity & Location */}
              <div className="space-y-4">
                <h4 className="flex items-center gap-2 font-semibold text-gray-900 dark:text-white text-sm uppercase tracking-wide">
                  <Icons.MapPin size={16} className="text-blue-500" /> Identity & Location
                </h4>
                
                {/* PROMINENT BUSINESS AGE SECTION */}
                <div className="flex items-center justify-between bg-blue-50 dark:bg-slate-700/50 p-3 rounded-lg border border-blue-100 dark:border-slate-600 shadow-sm">
                    <div>
                        <div className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Year Founded</div>
                        <div className="font-bold text-gray-900 dark:text-white text-lg">{data.yearFounded !== 'N/A' ? data.yearFounded : 'N/A'}</div>
                    </div>
                    {businessAge !== null && (
                        <div className="text-right border-l border-blue-200 dark:border-slate-500 pl-4">
                           <div className="text-[10px] text-gray-500 uppercase tracking-wider font-bold">Business Age</div>
                           <div className="font-bold text-blue-600 dark:text-blue-400 text-lg">{businessAge} Years</div>
                        </div>
                    )}
                </div>

                <div className="text-sm space-y-2 text-gray-600 dark:text-gray-300">
                   <p><span className="font-medium text-gray-900 dark:text-white">Keywords:</span> {data.keywords.join(', ')}</p>
                   <p><span className="font-medium text-gray-900 dark:text-white">Sub-category:</span> {data.subCategory}</p>
                   <p><span className="font-medium text-gray-900 dark:text-white">Service Area:</span> {data.serviceArea}</p>
                   <p><span className="font-medium text-gray-900 dark:text-white">Competitors Nearby:</span> {data.nearbyCompetitorsCount}</p>
                   <p><span className="font-medium text-gray-900 dark:text-white">Coords:</span> {data.latitude.toFixed(4)}, {data.longitude.toFixed(4)}</p>
                </div>
              </div>

              {/* Contact & Digital */}
              <div className="space-y-4">
                <h4 className="flex items-center gap-2 font-semibold text-gray-900 dark:text-white text-sm uppercase tracking-wide">
                  <Icons.Phone size={16} className="text-green-500" /> Contact & Digital
                </h4>
                <div className="text-sm space-y-2 text-gray-600 dark:text-gray-300">
                   <p className="flex items-center gap-2"><Icons.Phone size={14} /> {data.phone}</p>
                   {data.secondaryPhone !== 'N/A' && <p className="text-xs ml-6">{data.secondaryPhone}</p>}
                   <p className="flex items-center gap-2"><Icons.Mail size={14} /> {data.email}</p>
                   <div className="flex gap-3 mt-2">
                      {data.facebook && <span className="text-xs bg-blue-100 text-blue-800 px-2 py-1 rounded">FB</span>}
                      {data.instagram && <span className="text-xs bg-pink-100 text-pink-800 px-2 py-1 rounded">IG</span>}
                      {data.linkedin && <span className="text-xs bg-blue-100 text-blue-900 px-2 py-1 rounded">LI</span>}
                   </div>
                   <p className="text-xs text-gray-500 mt-1">Pattern: {data.emailPattern}</p>
                </div>
              </div>

              {/* Authority & Hours */}
              <div className="space-y-4">
                <h4 className="flex items-center gap-2 font-semibold text-gray-900 dark:text-white text-sm uppercase tracking-wide">
                  <Icons.Shield size={16} className="text-purple-500" /> Authority
                </h4>
                <div className="grid grid-cols-2 gap-4 text-sm">
                   <div className="bg-white dark:bg-gray-700 p-3 rounded-lg shadow-sm">
                      <div className="text-gray-500 text-xs">Total Reviews</div>
                      <div className="font-bold text-lg">{data.totalReviews}</div>
                   </div>
                   <div className="bg-white dark:bg-gray-700 p-3 rounded-lg shadow-sm">
                      <div className="text-gray-500 text-xs">Photos</div>
                      <div className="font-bold text-lg">{data.photosCount}</div>
                   </div>
                </div>
                <div className="text-xs text-gray-500">
                   <p><span className="font-medium">Hours:</span> {data.openingHours}</p>
                   <p><span className="font-medium">Peak:</span> {data.peakBusyHours}</p>
                </div>
              </div>

              {/* Website Intel - REDESIGNED */}
              <div className="space-y-4">
                <h4 className="flex items-center gap-2 font-semibold text-gray-900 dark:text-white text-sm uppercase tracking-wide">
                  <Icons.Globe size={16} className="text-cyan-500" /> Website Intel
                </h4>
                
                <div className="grid grid-cols-2 gap-3">
                    {/* SSL Card */}
                    <div className={`flex flex-col p-3 rounded-lg border ${data.sslStatus === 'Yes' ? 'bg-green-50/50 border-green-100 dark:bg-green-900/10 dark:border-green-800' : 'bg-red-50/50 border-red-100 dark:bg-red-900/10 dark:border-red-800'}`}>
                        <div className="flex items-center gap-1.5 mb-1">
                            {data.sslStatus === 'Yes' ? <Icons.Lock size={14} className="text-green-600 dark:text-green-400" /> : <Icons.Unlock size={14} className="text-red-600 dark:text-red-400" />}
                            <span className={`text-[10px] font-bold uppercase tracking-wider ${data.sslStatus === 'Yes' ? 'text-green-700 dark:text-green-300' : 'text-red-700 dark:text-red-300'}`}>SSL</span>
                        </div>
                        <div className={`text-sm font-semibold ${data.sslStatus === 'Yes' ? 'text-green-800 dark:text-green-200' : 'text-red-800 dark:text-red-200'}`}>
                            {data.sslStatus === 'Yes' ? 'Secure' : 'Unsecure'}
                        </div>
                    </div>

                    {/* Mobile Card */}
                    <div className={`flex flex-col p-3 rounded-lg border ${data.mobileFriendly === 'Yes' ? 'bg-blue-50/50 border-blue-100 dark:bg-blue-900/10 dark:border-blue-800' : 'bg-yellow-50/50 border-yellow-100 dark:bg-yellow-900/10 dark:border-yellow-800'}`}>
                        <div className="flex items-center gap-1.5 mb-1">
                            <Icons.Smartphone size={14} className={data.mobileFriendly === 'Yes' ? "text-blue-600 dark:text-blue-400" : "text-yellow-600 dark:text-yellow-400"} />
                            <span className={`text-[10px] font-bold uppercase tracking-wider ${data.mobileFriendly === 'Yes' ? 'text-blue-700 dark:text-blue-300' : 'text-yellow-700 dark:text-yellow-300'}`}>Mobile</span>
                        </div>
                        <div className={`text-sm font-semibold ${data.mobileFriendly === 'Yes' ? 'text-blue-800 dark:text-blue-200' : 'text-yellow-800 dark:text-yellow-200'}`}>
                            {data.mobileFriendly === 'Yes' ? 'Friendly' : 'Not Optimized'}
                        </div>
                    </div>
                </div>

                <div className="space-y-3 pt-1">
                   <div>
                      <div className="flex justify-between text-xs mb-1.5">
                          <span className="text-gray-600 dark:text-gray-400 flex items-center gap-1.5">
                              <Icons.Zap size={12} className="text-amber-500" /> 
                              Speed Score
                          </span>
                          <span className="font-mono font-medium">{data.speedScore}/100</span>
                      </div>
                      <ScoreBar value={data.speedScore} colorClass={data.speedScore > 70 ? 'bg-green-500' : data.speedScore > 40 ? 'bg-yellow-500' : 'bg-red-500'} />
                   </div>
                   
                   <div>
                      <div className="flex justify-between text-xs mb-1.5">
                          <span className="text-gray-600 dark:text-gray-400 flex items-center gap-1.5">
                              <Icons.Activity size={12} className="text-indigo-500" /> 
                              Domain Authority
                          </span>
                          <span className="font-mono font-medium">{data.domainAuthority}/100</span>
                      </div>
                      <ScoreBar value={data.domainAuthority} colorClass="bg-indigo-500" />
                   </div>
                </div>
                
                {/* Tech Stack - PROMINENT DISPLAY */}
                <div className="mt-2 pt-2 border-t border-gray-100 dark:border-gray-700">
                    <div className="flex items-center justify-between bg-gray-50 dark:bg-gray-700/50 p-2 rounded-md">
                        <div className="flex items-center gap-2">
                            <Icons.Layers size={14} className="text-gray-500 dark:text-gray-400" />
                            <span className="text-xs font-medium text-gray-600 dark:text-gray-300">Technology</span>
                        </div>
                        <span className="text-xs font-bold text-gray-900 dark:text-white px-2 py-0.5 bg-white dark:bg-gray-600 rounded shadow-sm border border-gray-100 dark:border-gray-500">
                            {data.techStack}
                        </span>
                    </div>
                </div>
              </div>

              {/* AI Intelligence Scores - VISUAL ENHANCEMENT */}
              <div className="space-y-4 col-span-1 md:col-span-2">
                <h4 className="flex items-center gap-2 font-semibold text-gray-900 dark:text-white text-sm uppercase tracking-wide">
                  <Icons.Brain size={16} className="text-rose-500" /> AI Intelligence Analysis
                </h4>
                <p className="text-sm italic text-gray-600 border-l-4 border-rose-200 pl-3 py-1">
                    "{t(data.summary, data.summary_bn)}"
                </p>
                
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-6 mt-4">
                   {/* Strength */}
                   <div className="flex flex-col gap-1">
                     <div className="flex justify-between text-xs text-gray-500">
                       <span>Strength</span>
                       <span className="font-bold text-gray-900 dark:text-white">{data.strengthScore}</span>
                     </div>
                     <ScoreBar value={data.strengthScore} colorClass="bg-green-600" />
                   </div>

                   {/* Weakness */}
                   <div className="flex flex-col gap-1">
                     <div className="flex justify-between text-xs text-gray-500">
                       <span>Weakness</span>
                       <span className="font-bold text-gray-900 dark:text-white">{data.weaknessScore}</span>
                     </div>
                     <ScoreBar value={data.weaknessScore} colorClass="bg-red-600" />
                   </div>

                   {/* Engagement */}
                   <div className="flex flex-col gap-1">
                     <div className="flex justify-between text-xs text-gray-500">
                       <span>Engagement</span>
                       <span className="font-bold text-gray-900 dark:text-white">{data.engagementScore}</span>
                     </div>
                     <ScoreBar value={data.engagementScore} colorClass="bg-blue-600" />
                   </div>

                   {/* Threat Level */}
                   <div className="flex flex-col gap-1 justify-center">
                     <div className="text-xs text-gray-500 mb-1">Threat Level</div>
                     <div className={`text-center py-1 px-2 rounded font-bold text-xs border ${
                        data.threatLevel === 'High' 
                            ? 'bg-red-50 text-red-700 border-red-200 dark:bg-red-900/30 dark:text-red-300' 
                            : data.threatLevel === 'Medium'
                                ? 'bg-yellow-50 text-yellow-700 border-yellow-200 dark:bg-yellow-900/30 dark:text-yellow-300'
                                : 'bg-green-50 text-green-700 border-green-200 dark:bg-green-900/30 dark:text-green-300'
                     }`}>
                        {data.threatLevel}
                     </div>
                   </div>
                </div>

                <div className="mt-4 grid grid-cols-1 sm:grid-cols-2 gap-4">
                  <div className="bg-blue-50 dark:bg-gray-800 p-3 rounded-md">
                     <h5 className="text-xs font-bold text-blue-700 uppercase mb-2">Ideal Customer</h5>
                     <p className="text-sm text-gray-700 dark:text-gray-300">
                         {t(data.idealCustomer, data.idealCustomer_bn)}
                     </p>
                  </div>
                   <div className="bg-purple-50 dark:bg-gray-800 p-3 rounded-md">
                     <div className="flex justify-between items-center mb-1">
                        <h5 className="text-xs font-bold text-purple-700 uppercase">Conversion Probability</h5>
                        <span className="text-xs text-purple-600 font-bold">{data.conversionProb}%</span>
                     </div>
                     {/* Conversion Bar */}
                     <div className="w-full bg-purple-200 dark:bg-gray-600 rounded-full h-2.5 overflow-hidden">
                        <div 
                          className="h-full bg-gradient-to-r from-purple-400 to-purple-600" 
                          style={{ width: `${data.conversionProb}%` }}
                        ></div>
                     </div>
                     <p className="text-[10px] text-gray-500 mt-1.5 text-right">Estimated based on digital presence</p>
                  </div>
                </div>
              </div>
              
              {/* SALES OPPORTUNITIES */}
              <div className="space-y-4 col-span-1 md:col-span-3 lg:col-span-3">
                 <h4 className="flex items-center gap-2 font-semibold text-gray-900 dark:text-white text-sm uppercase tracking-wide">
                  <Icons.TrendingUp size={16} className="text-orange-500" /> Sales Opportunities & Hooks
                </h4>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {/* Top Opportunities */}
                  <div className="bg-orange-50 dark:bg-gray-800 border border-orange-100 dark:border-gray-700 rounded-lg p-4">
                     <h5 className="text-xs font-bold text-orange-700 dark:text-orange-400 uppercase mb-2">🔥 Top Sales Opportunities</h5>
                     {data.salesOpportunities && data.salesOpportunities.length > 0 ? (
                        <div className="flex flex-wrap gap-2">
                            {t(data.salesOpportunities, data.salesOpportunities_bn).map((opp: string, i: number) => (
                                <span key={i} className="inline-block px-2 py-1 bg-white dark:bg-gray-700 text-orange-800 dark:text-orange-300 text-xs font-medium rounded border border-orange-200 dark:border-gray-600 shadow-sm">
                                    {opp}
                                </span>
                            ))}
                        </div>
                     ) : (
                        <p className="text-xs text-gray-500">No specific opportunities detected by AI.</p>
                     )}
                  </div>
                   <div className="bg-white dark:bg-gray-700 border border-gray-100 dark:border-gray-600 rounded-lg p-4">
                     <h5 className="text-xs font-bold text-gray-500 uppercase mb-2">Killer Hooks</h5>
                     <ul className="list-disc list-inside space-y-1">
                        {t(data.marketingHooks, data.marketingHooks_bn).slice(0,5).map((hook: string, i: number) => (
                          <li key={i} className="text-sm text-gray-700 dark:text-gray-200">{hook}</li>
                        ))}
                     </ul>
                  </div>
                </div>
              </div>

            </div>
            )}

            {/* TAB CONTENT: OUTREACH GENERATOR (NEW) */}
            {activeTab === 'outreach' && (
              <div className="p-6 border-b border-gray-200 dark:border-gray-700 bg-gray-50/50 dark:bg-gray-900/30">
                 <div className="max-w-3xl mx-auto">
                    <div className="mb-6">
                        <h4 className="text-lg font-bold text-gray-900 dark:text-white mb-2">AI Sales Outreach Script</h4>
                        <p className="text-sm text-gray-500">
                           This script is auto-generated based on {data.businessName}'s specific weaknesses (
                           {!data.website ? 'No Website, ' : ''}
                           {data.googleRating < 4.5 ? 'Low Rating, ' : ''}
                           {!data.facebook ? 'Missing Socials' : 'General Optimization'}
                           ).
                        </p>
                    </div>

                    <div className="bg-white dark:bg-gray-800 rounded-xl shadow-sm border border-gray-200 dark:border-gray-600 overflow-hidden">
                       <div className="p-4 border-b border-gray-100 dark:border-gray-700 flex justify-between items-center bg-gray-50 dark:bg-gray-700/50">
                          <span className="text-xs font-bold text-gray-500 uppercase tracking-wide">Cold Email / Message Template</span>
                          <button 
                             onClick={handleCopy}
                             className="flex items-center gap-1.5 px-3 py-1.5 text-xs font-medium text-blue-600 bg-blue-50 hover:bg-blue-100 rounded-lg transition-colors"
                          >
                             {copied ? <Icons.Check size={14} /> : <Icons.Copy size={14} />}
                             {copied ? 'Copied!' : 'Copy to Clipboard'}
                          </button>
                       </div>
                       <div className="p-6 space-y-4">
                          <div>
                             <label className="block text-xs font-semibold text-gray-500 mb-1">Subject Line</label>
                             <div className="text-sm font-medium text-gray-900 dark:text-white border-b border-dashed border-gray-300 pb-2">
                                {outreachContent.subject}
                             </div>
                          </div>
                          <div>
                             <label className="block text-xs font-semibold text-gray-500 mb-1">Body</label>
                             <div className="text-sm text-gray-700 dark:text-gray-300 whitespace-pre-wrap leading-relaxed">
                                {outreachContent.body}
                             </div>
                          </div>
                       </div>
                       <div className="bg-yellow-50 dark:bg-yellow-900/20 p-3 text-xs text-yellow-800 dark:text-yellow-200 text-center border-t border-yellow-100 dark:border-yellow-900/50">
                          💡 Tip: Customize the first line to mention something specific about their recent reviews or photos!
                       </div>
                    </div>
                 </div>
              </div>
            )}
          </td>
        </tr>
      )}
    </>
  );
};